defaults: ../../../../examples/modelopt/qa_distillation_nano3_megatron.yaml
distillation:
  num_prompts_per_step: 4
  max_num_steps: 1
  val_period: 0
policy:
  disable_modelopt_layer_spec: false
  train_global_batch_size: 16
  max_total_sequence_length: 2048
  quant_calib_size: 16
  quant_sequence_length: 1024
  megatron_cfg:
    tensor_model_parallel_size: 1
    scheduler:
      lr_warmup_iters: 1
  generation:
    vllm_kwargs:
      tokenizer: nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B-BF16
logger:
  log_dir: logs/distillation-nano3-30ba3b-4n4g-megatron-qa-nvfp4-modelopt-spec
  wandb:
    project: nemo-rl
    name: distillation-nano3-30ba3b-4n4g-megatron-qa-nvfp4-modelopt-spec
  tensorboard:
    log_dir: tb_logs-distillation-nano3-30ba3b-4n4g-megatron-qa-nvfp4-modelopt-spec
cluster:
  gpus_per_node: 4
