defaults: ../../grpo_math_1B.yaml
grpo:
  num_prompts_per_step: 16
  num_generations_per_prompt: 8
checkpointing:
  checkpoint_dir: results/grpo-nemotron3-super-120BA12B-16n8g-automodel-ep8
policy:
  model_name: nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-BF16
  tokenizer:
    name: nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-BF16
  train_global_batch_size: 128
  train_micro_batch_size: 1
  logprob_batch_size: 1
  logprob_chunk_size: 2048
  max_total_sequence_length: 8192
  make_sequence_length_divisible_by: 8
  optimizer:
    name: transformer_engine.pytorch.optimizers.fused_adam.FusedAdam
    kwargs:
      master_weights: true
      store_param_remainders: true
      exp_avg_dtype: torch.bfloat16
      exp_avg_sq_dtype: torch.bfloat16
  dtensor_cfg:
    expert_parallel_size: 8
    activation_checkpointing: true
    env_vars:
      PYTORCH_CUDA_ALLOC_CONF: expandable_segments:True
    automodel_kwargs:
      backend:
        _target_: nemo_automodel.components.models.common.utils.BackendConfig
        attn: te
        linear: te
        rms_norm: te
        enable_deepep: true
        fake_balanced_gate: false
        rope_fusion: false
        enable_hf_state_dict_adapter: true
  sequence_packing:
    enabled: false
  dynamic_batching:
    enabled: true
  generation:
    vllm_cfg:
      tensor_parallel_size: 8
    vllm_kwargs:
      moe_backend: triton
logger:
  wandb_enabled: true
  tensorboard_enabled: true
  wandb:
    project: nemo-rl
    name: grpo-nemotron3-super-120BA12B-16n8g-automodel-ep8
cluster:
  gpus_per_node: 8
  num_nodes: 16
