defaults: ../../grpo_math_1B.yaml

grpo:
  max_num_steps: 500
  num_prompts_per_step: 4
  num_generations_per_prompt: 4

checkpointing:
  enabled: false
  checkpoint_dir: results/grpo-qwen3-1.7b-1n8g-megatron-eagle3
  save_period: 100

policy:
  model_name: Qwen/Qwen3-1.7B
  tokenizer:
    name: Qwen/Qwen3-1.7B
  optimizer: null
  megatron_cfg:
    enabled: true
    scheduler:
      lr_warmup_iters: 50
  dtensor_cfg:
    enabled: false
  make_sequence_length_divisible_by: 1
  train_global_batch_size: 16
  train_micro_batch_size: 1
  logprob_batch_size: 1
  sequence_packing:
    enabled: false
  draft:
    enabled: true
    model_name: AngelSlim/Qwen3-1.7B_eagle3
    loss_weight: 1.0
  generation:
    vllm_kwargs:
      speculative_config:
        method: "eagle3"
        model: ${policy.draft.model_name}
        num_speculative_tokens: 3
        draft_tensor_parallel_size: 1

logger:
  log_dir: logs/grpo-qwen3-1.7b-1n8g-megatron-eagle3
  wandb:
    name: grpo-qwen3-1.7b-1n8g-megatron-eagle3

cluster:
  gpus_per_node: 8
