defaults: ./grpo-qwen3-30ba3b-8n8g-megatron-cp2-r3.yaml
grpo:
  async_grpo:
    enabled: true
    in_flight_weight_updates: true
loss_fn:
  use_importance_sampling_correction: true
checkpointing:
  checkpoint_dir: results/grpo-qwen3-30ba3b-10n8g-megatron-cp2-r3-async
policy:
  generation:
    colocated:
      enabled: false
      resources:
        num_nodes: 2
        gpus_per_node: 8
    vllm_cfg:
      async_engine: true
logger:
  log_dir: logs/grpo-qwen3-30ba3b-10n8g-megatron-cp2-r3-async
  wandb:
    name: grpo-qwen3-30ba3b-10n8g-megatron-cp2-r3-async
cluster:
  num_nodes: 10
