defaults: ppo-qwen2.5-1.5b-gsm8k-1n8g-megatron-valuetp2sp-dynbatch.yaml
checkpointing:
  checkpoint_dir: results/ppo-qwen2.5-1.5b-gsm8k-1n8g-megatron-valuetp2sp-pp2cp2-pack
value:
  make_sequence_length_divisible_by: 8
  megatron_cfg:
    pipeline_model_parallel_size: 2
    context_parallel_size: 2
  dynamic_batching:
    enabled: false
  sequence_packing:
    enabled: true
logger:
  log_dir: logs/ppo-qwen2.5-1.5b-gsm8k-1n8g-megatron-valuetp2sp-pp2cp2-pack
  wandb:
    name: ppo-qwen2.5-1.5b-gsm8k-1n8g-megatron-valuetp2sp-pp2cp2-pack
