defaults: ../../grpo_math_1B_megatron.yaml
grpo:
  num_generations_per_prompt: 8
  max_num_steps: 1000
  val_at_start: true
checkpointing:
  enabled: true
  checkpoint_dir: results/audio_grpo_7B_megatron
  keep_top_k: 10
  save_period: 50
policy:
  model_name: Qwen/Qwen2.5-Omni-7B
  train_global_batch_size: 32
  train_micro_batch_size: 1
  generation_batch_size: 16
  logprob_batch_size: 1
  max_total_sequence_length: 2048
  sequence_packing:
    enabled: false
  generation:
    max_new_tokens: 1024
    vllm_cfg:
      skip_tokenizer_init: false
      tensor_parallel_size: 2
      gpu_memory_utilization: 0.55
    vllm_kwargs:
      mm_processor_cache_gb: 0
      limit_mm_per_prompt:
        audio: 1
  megatron_cfg:
    converter_type: Qwen2_5OmniForConditionalGeneration
    apply_rope_fusion: false
    tensor_model_parallel_size: 4
    optimizer:
      lr: 1.0e-06
      min_lr: 1.0e-07
    scheduler:
      lr_warmup_iters: 10
      lr_warmup_init: 1.0e-07
    distributed_data_parallel_config:
      overlap_grad_reduce: false
data:
  num_workers: 0
  train:
    dataset_name: audiomcq
    split: train
    split_validation_size: 256
    seed: 42
  default:
    prompt_file: null
    processor: vlm_hf_data_processor
    env_name: vlm
env:
  vlm:
    num_workers: 8
    reward_functions:
    - name: format
      weight: 0.2
    - name: exact_alnum
      weight: 0.8
logger:
  wandb_enabled: true
  tensorboard_enabled: true
  wandb:
    name: audio-grpo-7b-megatron
  swanlab:
    name: audio-grpo-7b-megatron
cluster:
  gpus_per_node: 8
