defaults: sft.yaml
sft:
  max_num_steps: 1000000
  val_period: 500
  val_batches: 4
  val_global_batch_size: 128
  val_micro_batch_size: 2
checkpointing:
  checkpoint_dir: results/sft_openmathinstruct2
  keep_top_k: 100
  save_period: 500
policy:
  model_name: meta-llama/Llama-3.1-8B
  tokenizer:
    name: meta-llama/Llama-3.1-8B-Instruct
  train_global_batch_size: 512
  train_micro_batch_size: 2
  max_total_sequence_length: 4096
  dtensor_cfg:
    tensor_parallel_size: 4
  max_grad_norm: null
  optimizer:
    kwargs:
      lr: 2.0e-05
      weight_decay: 0.01
      eps: 1.0e-08
data:
  add_generation_prompt: true
  train:
    dataset_name: OpenMathInstruct-2
    output_key: generated_solution
    split: train_1M
    split_validation_size: 0.05
    seed: ${sft.seed}
  validation: null
  default:
    prompt_file: examples/prompts/math.txt
logger:
  monitor_gpus: false
  wandb:
    name: openmathinstruct-nemorl-1M_train
  swanlab:
    name: openmathinstruct-nemorl-1M_train
  tensorboard:
    log_dir: tb_logs-openmathinstruct-nemorl-1M_train
  mlflow:
    run_name: openmathinstruct-nemorl-1M_train
cluster:
  gpus_per_node: 8
